language: node_js
node_js:
  - "7"
install:
  - git clone https://github.com/churuxu/gmp
  - chmod +x gmp/gmp
  - export PATH=$PATH:$(pwd)/gmp
script:
  - chmod +x test.sh
  - ./test.sh
branches:
  only:
    - master 
    